# Generated by Django 2.2 on 2021-04-27 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opros',
            fields=[
                ('id', models.CharField(default='num', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.CharField(default=datetime.datetime(2021, 4, 27, 22, 50, 41, 268138), max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('discrip', models.CharField(max_length=255)),
            ],
        ),
    ]
