# Generated by Django 2.2 on 2021-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fab_resh', '0003_auto_20210427_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opros',
            name='start',
            field=models.CharField(default='2021-04-27 23:21:46', max_length=255),
        ),
    ]
