# Generated by Django 2.2 on 2021-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fab_resh', '0004_auto_20210427_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opros',
            name='start',
            field=models.CharField(default='2021-04-27 23:24:17', max_length=255),
        ),
    ]
